apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: netology-web
  name: netology-web
spec:
  containers:
  - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    name: netology-web
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
