apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: netology-web
  name: netology-svc
spec:
  ports:
  - port: 28080
    protocol: TCP
    targetPort: 8080
  selector:
    run: netology-web
status:
  loadBalancer: {}
