#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
    %{~ for ssh_key in ssh_keys ~}
      - ${ssh_key}
    %{~ endfor ~}
package_update: true
package_upgrade: false
packages:
  - vim
  - nginx
